import { useNavigate } from 'react-router-dom'

export default function TermsPage() {
  const nav = useNavigate()
  const sections = [
    { title: '1. Acceptance of Terms', body: 'By creating an account and using HabitStack, you agree to these Terms of Service. If you do not agree, please do not use the app. We reserve the right to update these terms, and continued use after changes means you accept the updated terms.' },
    { title: '2. Account Responsibilities', body: 'You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during signup. You may not create accounts for others without their consent, or use the app for any unlawful purpose. One account per person.' },
    { title: '3. Acceptable Use', body: 'HabitStack is a personal productivity tool. You agree not to: attempt to access other users\' private data, reverse engineer or scrape the app, use automated bots to manipulate leaderboard scores, or harass other users via any social feature. Violations may result in immediate account termination.' },
    { title: '4. Privacy & Data', body: 'Your use of HabitStack is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the app, you consent to the data practices described in the Privacy Policy.' },
    { title: '5. Intellectual Property', body: 'HabitStack, its logo, design, and original content are owned by the developers. You may not copy, reproduce, or distribute any part of the app without explicit written permission. Your personal habit data remains yours.' },
    { title: '6. AI Coach Feature', body: 'The AI Coach feature is powered by Anthropic\'s Claude. Coaching advice is generated by an AI and is not a substitute for professional medical, psychological, or fitness advice. Use AI suggestions at your own discretion. We are not responsible for any outcomes based on AI-generated content.' },
    { title: '7. Service Availability', body: 'We strive for high availability but do not guarantee 100% uptime. The app may be temporarily unavailable for maintenance or due to circumstances outside our control. We are not liable for any loss resulting from service interruptions.' },
    { title: '8. Early Access & Pricing', body: 'HabitStack is currently in early access and free for all users. We reserve the right to introduce paid plans in the future. Early users who signed up during the free period will be given fair notice of any pricing changes, and free tier access will always remain available with core features.' },
    { title: '9. Termination', body: 'You may delete your account at any time. We may suspend or terminate accounts that violate these Terms, with or without prior notice. Upon termination, your data will be deleted per our Privacy Policy.' },
    { title: '10. Limitation of Liability', body: 'HabitStack is provided "as is." We make no warranties of any kind. To the fullest extent permitted by law, we are not liable for any direct, indirect, incidental, or consequential damages arising from your use of the app.' },
    { title: '11. Governing Law', body: 'These Terms are governed by the laws of India. Any disputes shall be resolved in the courts of Karnataka, India.' },
    { title: '12. Contact', body: 'For questions about these Terms, contact us at: legal@habitstack.app' },
  ]

  return (
    <div style={{ minHeight: '100dvh', background: '#0a0a0a', color: '#f5f5f5', fontFamily: "'Barlow', sans-serif", padding: '0 20px 60px' }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@700;900&family=Barlow:wght@300;400;500&display=swap'); .bc{font-family:'Barlow Condensed',sans-serif;}`}</style>
      <div style={{ maxWidth: 680, margin: '0 auto' }}>
        <div style={{ padding: '60px 0 32px' }}>
          <button onClick={() => nav('/')} style={{ background: 'transparent', border: 'none', color: '#555', fontSize: 13, cursor: 'pointer', marginBottom: 20, padding: 0 }}>← Back</button>
          <div className="bc" style={{ fontSize: 36, fontWeight: 900, color: '#ff5000', letterSpacing: -1, marginBottom: 6 }}>TERMS OF SERVICE</div>
          <div style={{ fontSize: 13, color: '#555' }}>Last updated: April 2026 · HabitStack</div>
        </div>
        {sections.map((s, i) => (
          <div key={i} style={{ marginBottom: 24 }}>
            <div className="bc" style={{ fontSize: 16, fontWeight: 900, color: '#f5f5f5', marginBottom: 8, letterSpacing: 0.5 }}>{s.title}</div>
            <div style={{ fontSize: 14, color: '#888', lineHeight: 1.8 }}>{s.body}</div>
          </div>
        ))}
      </div>
    </div>
  )
}
